@includefrom Objectool.asm
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; These are pointers to extended objects 98-FF.  Don't change them.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

dw CustObj98
dw CustObj99
dw CustObj9A
dw CustObj9B
dw CustObj9C
dw CustObj9D
dw CustObj9E
dw CustObj9F
dw CustObjA0
dw CustObjA1
dw CustObjA2
dw CustObjA3
dw CustObjA4
dw CustObjA5
dw CustObjA6
dw CustObjA7
dw CustObjA8
dw CustObjA9
dw CustObjAA
dw CustObjAB
dw CustObjAC
dw CustObjAD
dw CustObjAE
dw CustObjAF
dw CustObjB0
dw CustObjB1
dw CustObjB2
dw CustObjB3
dw CustObjB4
dw CustObjB5
dw CustObjB6
dw CustObjB7
dw CustObjB8
dw CustObjB9
dw CustObjBA
dw CustObjBB
dw CustObjBC
dw CustObjBD
dw CustObjBE
dw CustObjBF
dw CustObjC0
dw CustObjC1
dw CustObjC2
dw CustObjC3
dw CustObjC4
dw CustObjC5
dw CustObjC6
dw CustObjC7
dw CustObjC8
dw CustObjC9
dw CustObjCA
dw CustObjCB
dw CustObjCC
dw CustObjCD
dw CustObjCE
dw CustObjCF
dw CustObjD0
dw CustObjD1
dw CustObjD2
dw CustObjD3
dw CustObjD4
dw CustObjD5
dw CustObjD6
dw CustObjD7
dw CustObjD8
dw CustObjD9
dw CustObjDA
dw CustObjDB
dw CustObjDC
dw CustObjDD
dw CustObjDE
dw CustObjDF
dw CustObjE0
dw CustObjE1
dw CustObjE2
dw CustObjE3
dw CustObjE4
dw CustObjE5
dw CustObjE6
dw CustObjE7
dw CustObjE8
dw CustObjE9
dw CustObjEA
dw CustObjEB
dw CustObjEC
dw CustObjED
dw CustObjEE
dw CustObjEF
dw CustObjF0
dw CustObjF1
dw CustObjF2
dw CustObjF3
dw CustObjF4
dw CustObjF5
dw CustObjF6
dw CustObjF7
dw CustObjF8
dw CustObjF9
dw CustObjFA
dw CustObjFB
dw CustObjFC
dw CustObjFD
dw CustObjFE
dw CustObjFF